version: "3.9"
services:
  service:
    build: .
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 128M
    ports:
      - "50051:50051"
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  grafana:
      image: grafana/grafana:8.1.1
      ports:
        - '3000:3000'
      volumes:
        - grafana-data:/var/lib/grafana
        - ./grafana-provisioning/:/etc/grafana/provisioning
      depends_on:
        - influxdb
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=1234
        - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/jmeter.json
volumes:
  influxdb-data:
  grafana-data:
